/**
 * 传入文件路径，返回此文件的 MIME Type。路径不含扩展名或找不到对应类型的，返回 null。
 * Given a file path, return the MIME Type of the file.
 * If the path does not contain an extension or if the type cannot be found, return null.
 */
export function path2MIMEType(path: string) {
  const dotIndex = path.lastIndexOf('.')
  if (dotIndex !== -1) return MIMETypesMap.get(path.slice(dotIndex)) ?? null
  return null
}

/*
Common MIME Types
Extract From：https://mimetype.io/all-types

[...document.querySelectorAll('section .title')].map(v => ({
    type: v.innerText,
    extensions: v.parentElement.querySelector('.extensions').innerText.split('\n')
}))
*/
export const MIMETypes = [
  { type: 'application/andrew-inset', extensions: ['.ez'] },
  { type: 'application/applixware', extensions: ['.aw'] },
  { type: 'application/atom+xml', extensions: ['.atom'] },
  { type: 'application/atomcat+xml', extensions: ['.atomcat'] },
  { type: 'application/atomsvc+xml', extensions: ['.atomsvc'] },
  { type: 'application/ccxml+xml', extensions: ['.ccxml'] },
  { type: 'application/cu-seeme', extensions: ['.cu'] },
  { type: 'application/davmount+xml', extensions: ['.davmount'] },
  { type: 'application/ecmascript', extensions: ['.ecma'] },
  { type: 'application/emma+xml', extensions: ['.emma'] },
  { type: 'application/epub+zip', extensions: ['.epub'] },
  { type: 'application/font-tdpfr', extensions: ['.pfr'] },
  { type: 'application/gzip', extensions: ['.gz', '.tgz'] },
  { type: 'application/hyperstudio', extensions: ['.stk'] },
  { type: 'application/java-archive', extensions: ['.jar'] },
  { type: 'application/java-serialized-object', extensions: ['.ser'] },
  { type: 'application/java-vm', extensions: ['.class'] },
  { type: 'application/json', extensions: ['.json'] },
  { type: 'application/lost+xml', extensions: ['.lostxml'] },
  { type: 'application/mac-binhex40', extensions: ['.hqx'] },
  { type: 'application/mac-compactpro', extensions: ['.cpt'] },
  { type: 'application/marc', extensions: ['.mrc'] },
  { type: 'application/mathematica', extensions: ['.ma', '.mb', '.nb'] },
  { type: 'application/mathml+xml', extensions: ['.mathml', '.mml'] },
  { type: 'application/mbox', extensions: ['.mbox'] },
  { type: 'application/mediaservercontrol+xml', extensions: ['.mscml'] },
  { type: 'application/mp4', extensions: ['.mp4s'] },
  { type: 'application/msword', extensions: ['.doc', '.dot', '.wiz'] },
  { type: 'application/mxf', extensions: ['.mxf'] },
  {
    type: 'application/octet-stream',
    extensions: [
      '.a',
      '.bin',
      '.bpk',
      '.deploy',
      '.dist',
      '.distz',
      '.dmg',
      '.dms',
      '.dump',
      '.elc',
      '.iso',
      '.lha',
      '.lrf',
      '.lzh',
      '.o',
      '.obj',
      '.pkg',
      '.so',
    ],
  },
  { type: 'application/oda', extensions: ['.oda'] },
  { type: 'application/oebps-package+xml', extensions: ['.opf'] },
  { type: 'application/ogg', extensions: ['.ogx'] },
  { type: 'application/onenote', extensions: ['.onepkg', '.onetmp', '.onetoc', '.onetoc2'] },
  { type: 'application/patch-ops-error+xml', extensions: ['.xer'] },
  { type: 'application/pdf', extensions: ['.pdf'] },
  { type: 'application/pgp-encrypted', extensions: ['.pgp'] },
  { type: 'application/pgp-signature', extensions: ['.asc', '.sig'] },
  { type: 'application/pics-rules', extensions: ['.prf'] },
  { type: 'application/pkcs10', extensions: ['.p10'] },
  { type: 'application/pkcs7-mime', extensions: ['.p7c', '.p7m'] },
  { type: 'application/pkcs7-signature', extensions: ['.p7s'] },
  { type: 'application/pkix-cert', extensions: ['.cer'] },
  { type: 'application/pkix-crl', extensions: ['.crl'] },
  { type: 'application/pkix-pkipath', extensions: ['.pkipath'] },
  { type: 'application/pkixcmp', extensions: ['.pki'] },
  { type: 'application/pls+xml', extensions: ['.pls'] },
  { type: 'application/postscript', extensions: ['.ai', '.eps', '.ps'] },
  { type: 'application/prs.cww', extensions: ['.cww'] },
  { type: 'application/rdf+xml', extensions: ['.rdf'] },
  { type: 'application/reginfo+xml', extensions: ['.rif'] },
  { type: 'application/relax-ng-compact-syntax', extensions: ['.rnc'] },
  { type: 'application/resource-lists+xml', extensions: ['.rl'] },
  { type: 'application/resource-lists-diff+xml', extensions: ['.rld'] },
  { type: 'application/rls-services+xml', extensions: ['.rs'] },
  { type: 'application/rsd+xml', extensions: ['.rsd'] },
  { type: 'application/rss+xml', extensions: ['.rss'] },
  { type: 'application/rtf', extensions: ['.rtf'] },
  { type: 'application/sbml+xml', extensions: ['.sbml'] },
  { type: 'application/scvp-cv-request', extensions: ['.scq'] },
  { type: 'application/scvp-cv-response', extensions: ['.scs'] },
  { type: 'application/scvp-vp-request', extensions: ['.spq'] },
  { type: 'application/scvp-vp-response', extensions: ['.spp'] },
  { type: 'application/sdp', extensions: ['.sdp'] },
  { type: 'application/set-payment-initiation', extensions: ['.setpay'] },
  { type: 'application/set-registration-initiation', extensions: ['.setreg'] },
  { type: 'application/shf+xml', extensions: ['.shf'] },
  { type: 'application/smil+xml', extensions: ['.smi', '.smil'] },
  { type: 'application/sparql-query', extensions: ['.rq'] },
  { type: 'application/sparql-results+xml', extensions: ['.srx'] },
  { type: 'application/srgs', extensions: ['.gram'] },
  { type: 'application/srgs+xml', extensions: ['.grxml'] },
  { type: 'application/ssml+xml', extensions: ['.ssml'] },
  { type: 'application/vnd.3gpp.pic-bw-large', extensions: ['.plb'] },
  { type: 'application/vnd.3gpp.pic-bw-small', extensions: ['.psb'] },
  { type: 'application/vnd.3gpp.pic-bw-var', extensions: ['.pvb'] },
  { type: 'application/vnd.3gpp2.tcap', extensions: ['.tcap'] },
  { type: 'application/vnd.3m.post-it-notes', extensions: ['.pwn'] },
  { type: 'application/vnd.accpac.simply.aso', extensions: ['.aso'] },
  { type: 'application/vnd.accpac.simply.imp', extensions: ['.imp'] },
  { type: 'application/vnd.acucobol', extensions: ['.acu'] },
  { type: 'application/vnd.acucorp', extensions: ['.acutc', '.atc'] },
  { type: 'application/vnd.adobe.air-application-installer-package+zip', extensions: ['.air'] },
  { type: 'application/vnd.adobe.xdp+xml', extensions: ['.xdp'] },
  { type: 'application/vnd.adobe.xfdf', extensions: ['.xfdf'] },
  { type: 'application/vnd.airzip.filesecure.azf', extensions: ['.azf'] },
  { type: 'application/vnd.airzip.filesecure.azs', extensions: ['.azs'] },
  { type: 'application/vnd.amazon.ebook', extensions: ['.azw'] },
  { type: 'application/vnd.americandynamics.acc', extensions: ['.acc'] },
  { type: 'application/vnd.amiga.ami', extensions: ['.ami'] },
  { type: 'application/vnd.android.package-archive', extensions: ['.apk'] },
  { type: 'application/vnd.anser-web-certificate-issue-initiation', extensions: ['.cii'] },
  { type: 'application/vnd.anser-web-funds-transfer-initiation', extensions: ['.fti'] },
  { type: 'application/vnd.antix.game-component', extensions: ['.atx'] },
  { type: 'application/vnd.apple.installer+xml', extensions: ['.mpkg'] },
  { type: 'application/vnd.arastra.swi', extensions: ['.swi'] },
  { type: 'application/vnd.audiograph', extensions: ['.aep'] },
  { type: 'application/vnd.blueice.multipass', extensions: ['.mpm'] },
  { type: 'application/vnd.bmi', extensions: ['.bmi'] },
  { type: 'application/vnd.businessobjects', extensions: ['.rep'] },
  { type: 'application/vnd.chemdraw+xml', extensions: ['.cdxml'] },
  { type: 'application/vnd.chipnuts.karaoke-mmd', extensions: ['.mmd'] },
  { type: 'application/vnd.cinderella', extensions: ['.cdy'] },
  { type: 'application/vnd.claymore', extensions: ['.cla'] },
  { type: 'application/vnd.clonk.c4group', extensions: ['.c4d', '.c4f', '.c4g', '.c4p', '.c4u'] },
  { type: 'application/vnd.commonspace', extensions: ['.csp'] },
  { type: 'application/vnd.contact.cmsg', extensions: ['.cdbcmsg'] },
  { type: 'application/vnd.cosmocaller', extensions: ['.cmc'] },
  { type: 'application/vnd.crick.clicker', extensions: ['.clkx'] },
  { type: 'application/vnd.crick.clicker.keyboard', extensions: ['.clkk'] },
  { type: 'application/vnd.crick.clicker.palette', extensions: ['.clkp'] },
  { type: 'application/vnd.crick.clicker.template', extensions: ['.clkt'] },
  { type: 'application/vnd.crick.clicker.wordbank', extensions: ['.clkw'] },
  { type: 'application/vnd.criticaltools.wbs+xml', extensions: ['.wbs'] },
  { type: 'application/vnd.ctc-posml', extensions: ['.pml'] },
  { type: 'application/vnd.cups-ppd', extensions: ['.ppd'] },
  { type: 'application/vnd.curl.car', extensions: ['.car'] },
  { type: 'application/vnd.curl.pcurl', extensions: ['.pcurl'] },
  { type: 'application/vnd.data-vision.rdz', extensions: ['.rdz'] },
  { type: 'application/vnd.debian.binary-package', extensions: ['.deb', '.udeb'] },
  { type: 'application/vnd.denovo.fcselayout-link', extensions: ['.fe_launch'] },
  { type: 'application/vnd.dna', extensions: ['.dna'] },
  { type: 'application/vnd.dolby.mlp', extensions: ['.mlp'] },
  { type: 'application/vnd.dpgraph', extensions: ['.dpg'] },
  { type: 'application/vnd.dreamfactory', extensions: ['.dfac'] },
  { type: 'application/vnd.dynageo', extensions: ['.geo'] },
  { type: 'application/vnd.ecowin.chart', extensions: ['.mag'] },
  { type: 'application/vnd.enliven', extensions: ['.nml'] },
  { type: 'application/vnd.epson.esf', extensions: ['.esf'] },
  { type: 'application/vnd.epson.msf', extensions: ['.msf'] },
  { type: 'application/vnd.epson.quickanime', extensions: ['.qam'] },
  { type: 'application/vnd.epson.salt', extensions: ['.slt'] },
  { type: 'application/vnd.epson.ssf', extensions: ['.ssf'] },
  { type: 'application/vnd.eszigno3+xml', extensions: ['.es3', '.et3'] },
  { type: 'application/vnd.ezpix-album', extensions: ['.ez2'] },
  { type: 'application/vnd.ezpix-package', extensions: ['.ez3'] },
  { type: 'application/vnd.fdf', extensions: ['.fdf'] },
  { type: 'application/vnd.fdsn.mseed', extensions: ['.mseed'] },
  { type: 'application/vnd.fdsn.seed', extensions: ['.dataless', '.seed'] },
  { type: 'application/vnd.flographit', extensions: ['.gph'] },
  { type: 'application/vnd.fluxtime.clip', extensions: ['.ftc'] },
  { type: 'application/vnd.framemaker', extensions: ['.book', '.fm', '.frame', '.maker'] },
  { type: 'application/vnd.frogans.fnc', extensions: ['.fnc'] },
  { type: 'application/vnd.frogans.ltf', extensions: ['.ltf'] },
  { type: 'application/vnd.fsc.weblaunch', extensions: ['.fsc'] },
  { type: 'application/vnd.fujitsu.oasys', extensions: ['.oas'] },
  { type: 'application/vnd.fujitsu.oasys2', extensions: ['.oa2'] },
  { type: 'application/vnd.fujitsu.oasys3', extensions: ['.oa3'] },
  { type: 'application/vnd.fujitsu.oasysgp', extensions: ['.fg5'] },
  { type: 'application/vnd.fujitsu.oasysprs', extensions: ['.bh2'] },
  { type: 'application/vnd.fujixerox.ddd', extensions: ['.ddd'] },
  { type: 'application/vnd.fujixerox.docuworks', extensions: ['.xdw'] },
  { type: 'application/vnd.fujixerox.docuworks.binder', extensions: ['.xbd'] },
  { type: 'application/vnd.fuzzysheet', extensions: ['.fzs'] },
  { type: 'application/vnd.genomatix.tuxedo', extensions: ['.txd'] },
  { type: 'application/vnd.geogebra.file', extensions: ['.ggb'] },
  { type: 'application/vnd.geogebra.tool', extensions: ['.ggt'] },
  { type: 'application/vnd.geometry-explorer', extensions: ['.gex', '.gre'] },
  { type: 'application/vnd.gmx', extensions: ['.gmx'] },
  { type: 'application/vnd.google-earth.kml+xml', extensions: ['.kml'] },
  { type: 'application/vnd.google-earth.kmz', extensions: ['.kmz'] },
  { type: 'application/vnd.grafeq', extensions: ['.gqf', '.gqs'] },
  { type: 'application/vnd.groove-account', extensions: ['.gac'] },
  { type: 'application/vnd.groove-help', extensions: ['.ghf'] },
  { type: 'application/vnd.groove-identity-message', extensions: ['.gim'] },
  { type: 'application/vnd.groove-injector', extensions: ['.grv'] },
  { type: 'application/vnd.groove-tool-message', extensions: ['.gtm'] },
  { type: 'application/vnd.groove-tool-template', extensions: ['.tpl'] },
  { type: 'application/vnd.groove-vcard', extensions: ['.vcg'] },
  { type: 'application/vnd.handheld-entertainment+xml', extensions: ['.zmm'] },
  { type: 'application/vnd.hbci', extensions: ['.hbci'] },
  { type: 'application/vnd.hhe.lesson-player', extensions: ['.les'] },
  { type: 'application/vnd.hp-hpgl', extensions: ['.hpgl'] },
  { type: 'application/vnd.hp-hpid', extensions: ['.hpid'] },
  { type: 'application/vnd.hp-hps', extensions: ['.hps'] },
  { type: 'application/vnd.hp-jlyt', extensions: ['.jlt'] },
  { type: 'application/vnd.hp-pcl', extensions: ['.pcl'] },
  { type: 'application/vnd.hp-pclxl', extensions: ['.pclxl'] },
  { type: 'application/vnd.hydrostatix.sof-data', extensions: ['.sfd-hdstx'] },
  { type: 'application/vnd.hzn-3d-crossword', extensions: ['.x3d'] },
  { type: 'application/vnd.ibm.minipay', extensions: ['.mpy'] },
  { type: 'application/vnd.ibm.modcap', extensions: ['.afp', '.list3820', '.listafp'] },
  { type: 'application/vnd.ibm.rights-management', extensions: ['.irm'] },
  { type: 'application/vnd.ibm.secure-container', extensions: ['.sc'] },
  { type: 'application/vnd.iccprofile', extensions: ['.icc', '.icm'] },
  { type: 'application/vnd.igloader', extensions: ['.igl'] },
  { type: 'application/vnd.immervision-ivp', extensions: ['.ivp'] },
  { type: 'application/vnd.immervision-ivu', extensions: ['.ivu'] },
  { type: 'application/vnd.intercon.formnet', extensions: ['.xpw', '.xpx'] },
  { type: 'application/vnd.intu.qbo', extensions: ['.qbo'] },
  { type: 'application/vnd.intu.qfx', extensions: ['.qfx'] },
  { type: 'application/vnd.ipunplugged.rcprofile', extensions: ['.rcprofile'] },
  { type: 'application/vnd.irepository.package+xml', extensions: ['.irp'] },
  { type: 'application/vnd.is-xpr', extensions: ['.xpr'] },
  { type: 'application/vnd.jam', extensions: ['.jam'] },
  { type: 'application/vnd.jcp.javame.midlet-rms', extensions: ['.rms'] },
  { type: 'application/vnd.jisp', extensions: ['.jisp'] },
  { type: 'application/vnd.joost.joda-archive', extensions: ['.joda'] },
  { type: 'application/vnd.kahootz', extensions: ['.ktr', '.ktz'] },
  { type: 'application/vnd.kde.karbon', extensions: ['.karbon'] },
  { type: 'application/vnd.kde.kchart', extensions: ['.chrt'] },
  { type: 'application/vnd.kde.kformula', extensions: ['.kfo'] },
  { type: 'application/vnd.kde.kivio', extensions: ['.flw'] },
  { type: 'application/vnd.kde.kontour', extensions: ['.kon'] },
  { type: 'application/vnd.kde.kpresenter', extensions: ['.kpr', '.kpt'] },
  { type: 'application/vnd.kde.kspread', extensions: ['.ksp'] },
  { type: 'application/vnd.kde.kword', extensions: ['.kwd', '.kwt'] },
  { type: 'application/vnd.kenameaapp', extensions: ['.htke'] },
  { type: 'application/vnd.kidspiration', extensions: ['.kia'] },
  { type: 'application/vnd.kinar', extensions: ['.kne', '.knp'] },
  { type: 'application/vnd.koan', extensions: ['.skd', '.skm', '.skp', '.skt'] },
  { type: 'application/vnd.kodak-descriptor', extensions: ['.sse'] },
  { type: 'application/vnd.llamagraphics.life-balance.desktop', extensions: ['.lbd'] },
  { type: 'application/vnd.llamagraphics.life-balance.exchange+xml', extensions: ['.lbe'] },
  { type: 'application/vnd.lotus-1-2-3', extensions: ['.123'] },
  { type: 'application/vnd.lotus-approach', extensions: ['.apr'] },
  { type: 'application/vnd.lotus-freelance', extensions: ['.pre'] },
  { type: 'application/vnd.lotus-notes', extensions: ['.nsf'] },
  { type: 'application/vnd.lotus-organizer', extensions: ['.org'] },
  { type: 'application/vnd.lotus-screencam', extensions: ['.scm'] },
  { type: 'application/vnd.lotus-wordpro', extensions: ['.lwp'] },
  { type: 'application/vnd.macports.portpkg', extensions: ['.portpkg'] },
  { type: 'application/vnd.mcd', extensions: ['.mcd'] },
  { type: 'application/vnd.medcalcdata', extensions: ['.mc1'] },
  { type: 'application/vnd.mediastation.cdkey', extensions: ['.cdkey'] },
  { type: 'application/vnd.mfer', extensions: ['.mwf'] },
  { type: 'application/vnd.mfmp', extensions: ['.mfm'] },
  { type: 'application/vnd.micrografx.flo', extensions: ['.flo'] },
  { type: 'application/vnd.micrografx.igx', extensions: ['.igx'] },
  { type: 'application/vnd.mif', extensions: ['.mif'] },
  { type: 'application/vnd.mobius.daf', extensions: ['.daf'] },
  { type: 'application/vnd.mobius.dis', extensions: ['.dis'] },
  { type: 'application/vnd.mobius.mbk', extensions: ['.mbk'] },
  { type: 'application/vnd.mobius.mqy', extensions: ['.mqy'] },
  { type: 'application/vnd.mobius.msl', extensions: ['.msl'] },
  { type: 'application/vnd.mobius.plc', extensions: ['.plc'] },
  { type: 'application/vnd.mobius.txf', extensions: ['.txf'] },
  { type: 'application/vnd.mophun.application', extensions: ['.mpn'] },
  { type: 'application/vnd.mophun.certificate', extensions: ['.mpc'] },
  { type: 'application/vnd.mozilla.xul+xml', extensions: ['.xul'] },
  { type: 'application/vnd.ms-artgalry', extensions: ['.cil'] },
  { type: 'application/vnd.ms-cab-compressed', extensions: ['.cab'] },
  {
    type: 'application/vnd.ms-excel',
    extensions: ['.xla', '.xlb', '.xlc', '.xlm', '.xls', '.xlt', '.xlw'],
  },
  { type: 'application/vnd.ms-excel.addin.macroenabled.12', extensions: ['.xlam'] },
  { type: 'application/vnd.ms-excel.sheet.binary.macroenabled.12', extensions: ['.xlsb'] },
  { type: 'application/vnd.ms-excel.sheet.macroenabled.12', extensions: ['.xlsm'] },
  { type: 'application/vnd.ms-excel.template.macroenabled.12', extensions: ['.xltm'] },
  { type: 'application/vnd.ms-fontobject', extensions: ['.eot'] },
  { type: 'application/vnd.ms-htmlhelp', extensions: ['.chm'] },
  { type: 'application/vnd.ms-ims', extensions: ['.ims'] },
  { type: 'application/vnd.ms-lrm', extensions: ['.lrm'] },
  { type: 'application/vnd.ms-pki.seccat', extensions: ['.cat'] },
  { type: 'application/vnd.ms-pki.stl', extensions: ['.stl'] },
  { type: 'application/vnd.ms-powerpoint', extensions: ['.pot', '.ppa', '.pps', '.ppt', '.pwz'] },
  { type: 'application/vnd.ms-powerpoint.addin.macroenabled.12', extensions: ['.ppam'] },
  { type: 'application/vnd.ms-powerpoint.presentation.macroenabled.12', extensions: ['.pptm'] },
  { type: 'application/vnd.ms-powerpoint.slide.macroenabled.12', extensions: ['.sldm'] },
  { type: 'application/vnd.ms-powerpoint.slideshow.macroenabled.12', extensions: ['.ppsm'] },
  { type: 'application/vnd.ms-powerpoint.template.macroenabled.12', extensions: ['.potm'] },
  { type: 'application/vnd.ms-project', extensions: ['.mpp', '.mpt'] },
  { type: 'application/vnd.ms-word.document.macroenabled.12', extensions: ['.docm'] },
  { type: 'application/vnd.ms-word.template.macroenabled.12', extensions: ['.dotm'] },
  { type: 'application/vnd.ms-works', extensions: ['.wcm', '.wdb', '.wks', '.wps'] },
  { type: 'application/vnd.ms-wpl', extensions: ['.wpl'] },
  { type: 'application/vnd.ms-xpsdocument', extensions: ['.xps'] },
  { type: 'application/vnd.mseq', extensions: ['.mseq'] },
  { type: 'application/vnd.musician', extensions: ['.mus'] },
  { type: 'application/vnd.muvee.style', extensions: ['.msty'] },
  { type: 'application/vnd.neurolanguage.nlu', extensions: ['.nlu'] },
  { type: 'application/vnd.noblenet-directory', extensions: ['.nnd'] },
  { type: 'application/vnd.noblenet-sealer', extensions: ['.nns'] },
  { type: 'application/vnd.noblenet-web', extensions: ['.nnw'] },
  { type: 'application/vnd.nokia.n-gage.data', extensions: ['.ngdat'] },
  { type: 'application/vnd.nokia.n-gage.symbian.install', extensions: ['.n-gage'] },
  { type: 'application/vnd.nokia.radio-preset', extensions: ['.rpst'] },
  { type: 'application/vnd.nokia.radio-presets', extensions: ['.rpss'] },
  { type: 'application/vnd.novadigm.edm', extensions: ['.edm'] },
  { type: 'application/vnd.novadigm.edx', extensions: ['.edx'] },
  { type: 'application/vnd.novadigm.ext', extensions: ['.ext'] },
  { type: 'application/vnd.oasis.opendocument.chart', extensions: ['.odc'] },
  { type: 'application/vnd.oasis.opendocument.chart-template', extensions: ['.otc'] },
  { type: 'application/vnd.oasis.opendocument.database', extensions: ['.odb'] },
  { type: 'application/vnd.oasis.opendocument.formula', extensions: ['.odf'] },
  { type: 'application/vnd.oasis.opendocument.formula-template', extensions: ['.odft'] },
  { type: 'application/vnd.oasis.opendocument.graphics', extensions: ['.odg'] },
  { type: 'application/vnd.oasis.opendocument.graphics-template', extensions: ['.otg'] },
  { type: 'application/vnd.oasis.opendocument.image', extensions: ['.odi'] },
  { type: 'application/vnd.oasis.opendocument.image-template', extensions: ['.oti'] },
  { type: 'application/vnd.oasis.opendocument.presentation', extensions: ['.odp'] },
  { type: 'application/vnd.oasis.opendocument.presentation-template', extensions: ['.otp'] },
  { type: 'application/vnd.oasis.opendocument.spreadsheet', extensions: ['.ods'] },
  { type: 'application/vnd.oasis.opendocument.spreadsheet-template', extensions: ['.ots'] },
  { type: 'application/vnd.oasis.opendocument.text', extensions: ['.odt'] },
  { type: 'application/vnd.oasis.opendocument.text-master', extensions: ['.otm'] },
  { type: 'application/vnd.oasis.opendocument.text-template', extensions: ['.ott'] },
  { type: 'application/vnd.oasis.opendocument.text-web', extensions: ['.oth'] },
  { type: 'application/vnd.olpc-sugar', extensions: ['.xo'] },
  { type: 'application/vnd.oma.dd2+xml', extensions: ['.dd2'] },
  { type: 'application/vnd.openofficeorg.extension', extensions: ['.oxt'] },
  {
    type: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    extensions: ['.pptx'],
  },
  {
    type: 'application/vnd.openxmlformats-officedocument.presentationml.slide',
    extensions: ['.sldx'],
  },
  {
    type: 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
    extensions: ['.ppsx'],
  },
  {
    type: 'application/vnd.openxmlformats-officedocument.presentationml.template',
    extensions: ['.potx'],
  },
  {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    extensions: ['.xlsx'],
  },
  {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
    extensions: ['.xltx'],
  },
  {
    type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    extensions: ['.docx'],
  },
  {
    type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
    extensions: ['.dotx'],
  },
  { type: 'application/vnd.osgi.dp', extensions: ['.dp'] },
  { type: 'application/vnd.palm', extensions: ['.oprc', '.pdb', '.pqa'] },
  { type: 'application/vnd.pg.format', extensions: ['.str'] },
  { type: 'application/vnd.pg.osasli', extensions: ['.ei6'] },
  { type: 'application/vnd.picsel', extensions: ['.efif'] },
  { type: 'application/vnd.pocketlearn', extensions: ['.plf'] },
  { type: 'application/vnd.powerbuilder6', extensions: ['.pbd'] },
  { type: 'application/vnd.previewsystems.box', extensions: ['.box'] },
  { type: 'application/vnd.proteus.magazine', extensions: ['.mgz'] },
  { type: 'application/vnd.publishare-delta-tree', extensions: ['.qps'] },
  { type: 'application/vnd.pvi.ptid1', extensions: ['.ptid'] },
  {
    type: 'application/vnd.quark.quarkxpress',
    extensions: ['.qwd', '.qwt', '.qxb', '.qxd', '.qxl', '.qxt'],
  },
  { type: 'application/vnd.recordare.musicxml', extensions: ['.mxl'] },
  { type: 'application/vnd.recordare.musicxml+xml', extensions: ['.musicxml'] },
  { type: 'application/vnd.rim.cod', extensions: ['.cod'] },
  { type: 'application/vnd.rn-realmedia', extensions: ['.rm'] },
  { type: 'application/vnd.route66.link66+xml', extensions: ['.link66'] },
  { type: 'application/vnd.seemail', extensions: ['.see'] },
  { type: 'application/vnd.sema', extensions: ['.sema'] },
  { type: 'application/vnd.semd', extensions: ['.semd'] },
  { type: 'application/vnd.semf', extensions: ['.semf'] },
  { type: 'application/vnd.shana.informed.formdata', extensions: ['.ifm'] },
  { type: 'application/vnd.shana.informed.formtemplate', extensions: ['.itp'] },
  { type: 'application/vnd.shana.informed.interchange', extensions: ['.iif'] },
  { type: 'application/vnd.shana.informed.package', extensions: ['.ipk'] },
  { type: 'application/vnd.simtech-mindmapper', extensions: ['.twd', '.twds'] },
  { type: 'application/vnd.smaf', extensions: ['.mmf'] },
  { type: 'application/vnd.smart.teacher', extensions: ['.teacher'] },
  { type: 'application/vnd.solent.sdkm+xml', extensions: ['.sdkd', '.sdkm'] },
  { type: 'application/vnd.spotfire.dxp', extensions: ['.dxp'] },
  { type: 'application/vnd.spotfire.sfs', extensions: ['.sfs'] },
  {
    type: 'application/vnd.sqlite3',
    extensions: ['.db', '.sqlite', '.sqlite3', '.db-wal', '.sqlite-wal', '.db-shm', '.sqlite-shm'],
  },
  { type: 'application/vnd.stardivision.calc', extensions: ['.sdc'] },
  { type: 'application/vnd.stardivision.draw', extensions: ['.sda'] },
  { type: 'application/vnd.stardivision.impress', extensions: ['.sdd'] },
  { type: 'application/vnd.stardivision.math', extensions: ['.smf'] },
  { type: 'application/vnd.stardivision.writer', extensions: ['.sdw', '.vor'] },
  { type: 'application/vnd.stardivision.writer-global', extensions: ['.sgl'] },
  { type: 'application/vnd.sun.xml.calc', extensions: ['.sxc'] },
  { type: 'application/vnd.sun.xml.calc.template', extensions: ['.stc'] },
  { type: 'application/vnd.sun.xml.draw', extensions: ['.sxd'] },
  { type: 'application/vnd.sun.xml.draw.template', extensions: ['.std'] },
  { type: 'application/vnd.sun.xml.impress', extensions: ['.sxi'] },
  { type: 'application/vnd.sun.xml.impress.template', extensions: ['.sti'] },
  { type: 'application/vnd.sun.xml.math', extensions: ['.sxm'] },
  { type: 'application/vnd.sun.xml.writer', extensions: ['.sxw'] },
  { type: 'application/vnd.sun.xml.writer.global', extensions: ['.sxg'] },
  { type: 'application/vnd.sun.xml.writer.template', extensions: ['.stw'] },
  { type: 'application/vnd.sus-calendar', extensions: ['.sus', '.susp'] },
  { type: 'application/vnd.svd', extensions: ['.svd'] },
  { type: 'application/vnd.symbian.install', extensions: ['.sis', '.sisx'] },
  { type: 'application/vnd.syncml+xml', extensions: ['.xsm'] },
  { type: 'application/vnd.syncml.dm+wbxml', extensions: ['.bdm'] },
  { type: 'application/vnd.syncml.dm+xml', extensions: ['.xdm'] },
  { type: 'application/vnd.tao.intent-module-archive', extensions: ['.tao'] },
  { type: 'application/vnd.tmobile-livetv', extensions: ['.tmo'] },
  { type: 'application/vnd.trid.tpt', extensions: ['.tpt'] },
  { type: 'application/vnd.triscape.mxs', extensions: ['.mxs'] },
  { type: 'application/vnd.trueapp', extensions: ['.tra'] },
  { type: 'application/vnd.ufdl', extensions: ['.ufd', '.ufdl'] },
  { type: 'application/vnd.uiq.theme', extensions: ['.utz'] },
  { type: 'application/vnd.umajin', extensions: ['.umj'] },
  { type: 'application/vnd.unity', extensions: ['.unityweb'] },
  { type: 'application/vnd.uoml+xml', extensions: ['.uoml'] },
  { type: 'application/vnd.vcx', extensions: ['.vcx'] },
  { type: 'application/vnd.visio', extensions: ['.vsd', '.vss', '.vst', '.vsw'] },
  { type: 'application/vnd.visionary', extensions: ['.vis'] },
  { type: 'application/vnd.vsf', extensions: ['.vsf'] },
  { type: 'application/vnd.wap.sic', extensions: ['.sic'] },
  { type: 'application/vnd.wap.slc', extensions: ['.slc'] },
  { type: 'application/vnd.wap.wbxml', extensions: ['.wbxml'] },
  { type: 'application/vnd.wap.wmlc', extensions: ['.wmlc'] },
  { type: 'application/vnd.wap.wmlscriptc', extensions: ['.wmlsc'] },
  { type: 'application/vnd.webturbo', extensions: ['.wtb'] },
  { type: 'application/vnd.wordperfect', extensions: ['.wpd'] },
  { type: 'application/vnd.wqd', extensions: ['.wqd'] },
  { type: 'application/vnd.wt.stf', extensions: ['.stf'] },
  { type: 'application/vnd.xara', extensions: ['.xar'] },
  { type: 'application/vnd.xfdl', extensions: ['.xfdl'] },
  { type: 'application/vnd.yamaha.hv-dic', extensions: ['.hvd'] },
  { type: 'application/vnd.yamaha.hv-script', extensions: ['.hvs'] },
  { type: 'application/vnd.yamaha.hv-voice', extensions: ['.hvp'] },
  { type: 'application/vnd.yamaha.openscoreformat', extensions: ['.osf'] },
  { type: 'application/vnd.yamaha.openscoreformat.osfpvg+xml', extensions: ['.osfpvg'] },
  { type: 'application/vnd.yamaha.smaf-audio', extensions: ['.saf'] },
  { type: 'application/vnd.yamaha.smaf-phrase', extensions: ['.spf'] },
  { type: 'application/vnd.yellowriver-custom-menu', extensions: ['.cmp'] },
  { type: 'application/vnd.zul', extensions: ['.zir', '.zirz'] },
  { type: 'application/vnd.zzazz.deck+xml', extensions: ['.zaz'] },
  { type: 'application/voicexml+xml', extensions: ['.vxml'] },
  { type: 'application/winhlp', extensions: ['.hlp'] },
  { type: 'application/wsdl+xml', extensions: ['.wsdl'] },
  { type: 'application/wspolicy+xml', extensions: ['.wspolicy'] },
  { type: 'application/x-7z-compressed', extensions: ['.7z'] },
  { type: 'application/x-abiword', extensions: ['.abw'] },
  { type: 'application/x-ace-compressed', extensions: ['.ace'] },
  { type: 'application/x-authorware-bin', extensions: ['.aab', '.u32', '.vox', '.x32'] },
  { type: 'application/x-authorware-map', extensions: ['.aam'] },
  { type: 'application/x-authorware-seg', extensions: ['.aas'] },
  { type: 'application/x-bcpio', extensions: ['.bcpio'] },
  { type: 'application/x-bittorrent', extensions: ['.torrent'] },
  { type: 'application/x-bzip', extensions: ['.bz'] },
  { type: 'application/x-bzip2', extensions: ['.boz', '.bz2'] },
  { type: 'application/x-cdlink', extensions: ['.vcd'] },
  { type: 'application/x-chat', extensions: ['.chat'] },
  { type: 'application/x-chess-pgn', extensions: ['.pgn'] },
  { type: 'application/x-cpio', extensions: ['.cpio'] },
  { type: 'application/x-csh', extensions: ['.csh'] },
  { type: 'application/x-debian-package', extensions: ['.deb', '.udeb'] },
  {
    type: 'application/x-director',
    extensions: ['.cct', '.cst', '.cxt', '.dcr', '.dir', '.dxr', '.fgd', '.swa', '.w3d'],
  },
  { type: 'application/x-doom', extensions: ['.wad'] },
  { type: 'application/x-dtbncx+xml', extensions: ['.ncx'] },
  { type: 'application/x-dtbook+xml', extensions: ['.dtb'] },
  { type: 'application/x-dtbresource+xml', extensions: ['.res'] },
  { type: 'application/x-dvi', extensions: ['.dvi'] },
  { type: 'application/x-font-bdf', extensions: ['.bdf'] },
  { type: 'application/x-font-ghostscript', extensions: ['.gsf'] },
  { type: 'application/x-font-linux-psf', extensions: ['.psf'] },
  { type: 'application/x-font-otf', extensions: ['.otf'] },
  { type: 'application/x-font-pcf', extensions: ['.pcf'] },
  { type: 'application/x-font-snf', extensions: ['.snf'] },
  { type: 'application/x-font-ttf', extensions: ['.ttc', '.ttf'] },
  { type: 'application/x-font-type1', extensions: ['.afm', '.pfa', '.pfb', '.pfm'] },
  { type: 'application/x-futuresplash', extensions: ['.spl'] },
  { type: 'application/x-gnumeric', extensions: ['.gnumeric'] },
  { type: 'application/x-gtar', extensions: ['.gtar'] },
  { type: 'application/x-gzip', extensions: ['.gz', '.tgz'] },
  { type: 'application/x-hdf', extensions: ['.hdf'] },
  { type: 'application/x-java-jnlp-file', extensions: ['.jnlp'] },
  { type: 'application/x-killustrator', extensions: ['.kil'] },
  { type: 'application/x-krita', extensions: ['.kra', '.krz'] },
  { type: 'application/x-latex', extensions: ['.latex'] },
  { type: 'application/x-mobipocket-ebook', extensions: ['.mobi', '.prc'] },
  { type: 'application/x-ms-application', extensions: ['.application'] },
  { type: 'application/x-ms-wmd', extensions: ['.wmd'] },
  { type: 'application/x-ms-wmz', extensions: ['.wmz'] },
  { type: 'application/x-ms-xbap', extensions: ['.xbap'] },
  { type: 'application/x-msaccess', extensions: ['.mdb'] },
  { type: 'application/x-msbinder', extensions: ['.obd'] },
  { type: 'application/x-mscardfile', extensions: ['.crd'] },
  { type: 'application/x-msclip', extensions: ['.clp'] },
  { type: 'application/x-msdownload', extensions: ['.bat', '.com', '.dll', '.exe', '.msi'] },
  { type: 'application/x-msmediaview', extensions: ['.m13', '.m14', '.mvb'] },
  { type: 'application/x-msmetafile', extensions: ['.wmf'] },
  { type: 'application/x-msmoney', extensions: ['.mny'] },
  { type: 'application/x-mspublisher', extensions: ['.pub'] },
  { type: 'application/x-msschedule', extensions: ['.scd'] },
  { type: 'application/x-msterminal', extensions: ['.trm'] },
  { type: 'application/x-mswrite', extensions: ['.wri'] },
  { type: 'application/x-netcdf', extensions: ['.cdf', '.nc'] },
  { type: 'application/x-perl', extensions: ['.pm', '.pl'] },
  { type: 'application/x-pkcs12', extensions: ['.p12', '.pfx'] },
  { type: 'application/x-pkcs7-certificates', extensions: ['.p7b', '.spc'] },
  { type: 'application/x-python-code', extensions: ['.pyc', '.pyo'] },
  { type: 'application/x-redhat-package-manager', extensions: ['.rpa'] },
  { type: 'application/x-rpm', extensions: ['.rpm'] },
  { type: 'application/x-sh', extensions: ['.sh'] },
  { type: 'application/x-shar', extensions: ['.shar'] },
  { type: 'application/x-shellscript', extensions: ['.sh'] },
  { type: 'application/x-shockwave-flash', extensions: ['.swf'] },
  { type: 'application/x-silverlight-app', extensions: ['.xap'] },
  { type: 'application/x-stuffit', extensions: ['.sit'] },
  { type: 'application/x-stuffitx', extensions: ['.sitx'] },
  { type: 'application/x-sv4cpio', extensions: ['.sv4cpio'] },
  { type: 'application/x-sv4crc', extensions: ['.sv4crc'] },
  { type: 'application/x-tar', extensions: ['.tar'] },
  { type: 'application/x-tcl', extensions: ['.tcl'] },
  { type: 'application/x-tex', extensions: ['.tex'] },
  { type: 'application/x-tex-tfm', extensions: ['.tfm'] },
  { type: 'application/x-texinfo', extensions: ['.texi', '.texinfo'] },
  { type: 'application/x-trash', extensions: [''] },
  { type: 'application/x-ustar', extensions: ['.ustar'] },
  { type: 'application/x-wais-source', extensions: ['.src'] },
  { type: 'application/x-x509-ca-cert', extensions: ['.crt', '.der'] },
  { type: 'application/x-xfig', extensions: ['.fig'] },
  { type: 'application/x-xpinstall', extensions: ['.xpi'] },
  { type: 'application/xenc+xml', extensions: ['.xenc'] },
  { type: 'application/xhtml+xml', extensions: ['.xht', '.xhtml'] },
  { type: 'application/xml', extensions: ['.xml', '.xpdl', '.xsl'] },
  { type: 'application/xml-dtd', extensions: ['.dtd'] },
  { type: 'application/xop+xml', extensions: ['.xop'] },
  { type: 'application/xslt+xml', extensions: ['.xslt'] },
  { type: 'application/xspf+xml', extensions: ['.xspf'] },
  { type: 'application/xv+xml', extensions: ['.mxml', '.xhvml', '.xvm', '.xvml'] },
  { type: 'application/zip', extensions: ['.zip'] },
  { type: 'audio/3gpp', extensions: ['.3gp'] },
  { type: 'audio/3gpp2', extensions: ['.3g2'] },
  { type: 'audio/adpcm', extensions: ['.adp'] },
  { type: 'audio/aiff', extensions: ['.aiff', '.aif', '.aff'] },
  { type: 'audio/basic', extensions: ['.au', '.snd'] },
  { type: 'audio/flac', extensions: ['.flac'] },
  { type: 'audio/midi', extensions: ['.kar', '.mid', '.midi', '.rmi'] },
  { type: 'audio/mp4', extensions: ['.mp4a'] },
  { type: 'audio/mpeg', extensions: ['.m2a', '.m3a', '.mp2', '.mp2a', '.mp3', '.mpga'] },
  { type: 'audio/ogg', extensions: ['.oga', '.ogg', '.spx'] },
  { type: 'audio/opus', extensions: ['.opus'] },
  { type: 'audio/vnd.digital-winds', extensions: ['.eol'] },
  { type: 'audio/vnd.dts', extensions: ['.dts'] },
  { type: 'audio/vnd.dts.hd', extensions: ['.dtshd'] },
  { type: 'audio/vnd.lucent.voice', extensions: ['.lvp'] },
  { type: 'audio/vnd.ms-playready.media.pya', extensions: ['.pya'] },
  { type: 'audio/vnd.nuera.ecelp4800', extensions: ['.ecelp4800'] },
  { type: 'audio/vnd.nuera.ecelp7470', extensions: ['.ecelp7470'] },
  { type: 'audio/vnd.nuera.ecelp9600', extensions: ['.ecelp9600'] },
  { type: 'audio/wav', extensions: ['.wav'] },
  { type: 'audio/webm', extensions: ['.weba'] },
  { type: 'audio/x-aac', extensions: ['.aac'] },
  { type: 'audio/x-aiff', extensions: ['.aif', '.aifc', '.aiff'] },
  { type: 'audio/x-matroska', extensions: ['.mka'] },
  { type: 'audio/x-mpegurl', extensions: ['.m3u'] },
  { type: 'audio/x-ms-wax', extensions: ['.wax'] },
  { type: 'audio/x-ms-wma', extensions: ['.wma'] },
  { type: 'audio/x-pn-realaudio', extensions: ['.ra', '.ram'] },
  { type: 'audio/x-pn-realaudio-plugin', extensions: ['.rmp'] },
  { type: 'chemical/x-cdx', extensions: ['.cdx'] },
  { type: 'chemical/x-cif', extensions: ['.cif'] },
  { type: 'chemical/x-cmdf', extensions: ['.cmdf'] },
  { type: 'chemical/x-cml', extensions: ['.cml'] },
  { type: 'chemical/x-csml', extensions: ['.csml'] },
  { type: 'chemical/x-xyz', extensions: ['.xyz'] },
  { type: 'font/otf', extensions: ['.otf'] },
  { type: 'font/woff', extensions: ['.woff'] },
  { type: 'font/woff2', extensions: ['.woff2'] },
  { type: 'gcode', extensions: ['.gcode'] },
  { type: 'image/avif', extensions: ['.avif', '.avifs'] },
  { type: 'image/bmp', extensions: ['.bmp'] },
  { type: 'image/cgm', extensions: ['.cgm'] },
  { type: 'image/g3fax', extensions: ['.g3'] },
  { type: 'image/gif', extensions: ['.gif'] },
  { type: 'image/heic', extensions: ['.heif', '.heic'] },
  { type: 'image/ief', extensions: ['.ief'] },
  {
    type: 'image/jpeg',
    extensions: ['.jpe', '.jpeg', '.jpg', '.pjpg', '.jfif', '.jfif-tbnl', '.jif'],
  },
  {
    type: 'image/pjpeg',
    extensions: ['.jpe', '.jpeg', '.jpg', '.pjpg', '.jfi', '.jfif', '.jfif-tbnl', '.jif'],
  },
  { type: 'image/png', extensions: ['.png'] },
  { type: 'image/prs.btif', extensions: ['.btif'] },
  { type: 'image/svg+xml', extensions: ['.svg', '.svgz'] },
  { type: 'image/tiff', extensions: ['.tif', '.tiff'] },
  { type: 'image/vnd.adobe.photoshop', extensions: ['.psd'] },
  { type: 'image/vnd.djvu', extensions: ['.djv', '.djvu'] },
  { type: 'image/vnd.dwg', extensions: ['.dwg'] },
  { type: 'image/vnd.dxf', extensions: ['.dxf'] },
  { type: 'image/vnd.fastbidsheet', extensions: ['.fbs'] },
  { type: 'image/vnd.fpx', extensions: ['.fpx'] },
  { type: 'image/vnd.fst', extensions: ['.fst'] },
  { type: 'image/vnd.fujixerox.edmics-mmr', extensions: ['.mmr'] },
  { type: 'image/vnd.fujixerox.edmics-rlc', extensions: ['.rlc'] },
  { type: 'image/vnd.ms-modi', extensions: ['.mdi'] },
  { type: 'image/vnd.net-fpx', extensions: ['.npx'] },
  { type: 'image/vnd.wap.wbmp', extensions: ['.wbmp'] },
  { type: 'image/vnd.xiff', extensions: ['.xif'] },
  { type: 'image/webp', extensions: ['.webp'] },
  { type: 'image/x-adobe-dng', extensions: ['.dng'] },
  { type: 'image/x-canon-cr2', extensions: ['.cr2'] },
  { type: 'image/x-canon-crw', extensions: ['.crw'] },
  { type: 'image/x-cmu-raster', extensions: ['.ras'] },
  { type: 'image/x-cmx', extensions: ['.cmx'] },
  { type: 'image/x-epson-erf', extensions: ['.erf'] },
  { type: 'image/x-freehand', extensions: ['.fh', '.fh4', '.fh5', '.fh7', '.fhc'] },
  { type: 'image/x-fuji-raf', extensions: ['.raf'] },
  { type: 'image/x-icon', extensions: ['.ico'] },
  { type: 'image/x-kodak-dcr', extensions: ['.dcr'] },
  { type: 'image/x-kodak-k25', extensions: ['.k25'] },
  { type: 'image/x-kodak-kdc', extensions: ['.kdc'] },
  { type: 'image/x-minolta-mrw', extensions: ['.mrw'] },
  { type: 'image/x-nikon-nef', extensions: ['.nef'] },
  { type: 'image/x-olympus-orf', extensions: ['.orf'] },
  { type: 'image/x-panasonic-raw', extensions: ['.raw', '.rw2', '.rwl'] },
  { type: 'image/x-pcx', extensions: ['.pcx'] },
  { type: 'image/x-pentax-pef', extensions: ['.pef', '.ptx'] },
  { type: 'image/x-pict', extensions: ['.pct', '.pic'] },
  { type: 'image/x-portable-anymap', extensions: ['.pnm'] },
  { type: 'image/x-portable-bitmap', extensions: ['.pbm'] },
  { type: 'image/x-portable-graymap', extensions: ['.pgm'] },
  { type: 'image/x-portable-pixmap', extensions: ['.ppm'] },
  { type: 'image/x-rgb', extensions: ['.rgb'] },
  { type: 'image/x-sigma-x3f', extensions: ['.x3f'] },
  { type: 'image/x-sony-arw', extensions: ['.arw'] },
  { type: 'image/x-sony-sr2', extensions: ['.sr2'] },
  { type: 'image/x-sony-srf', extensions: ['.srf'] },
  { type: 'image/x-xbitmap', extensions: ['.xbm'] },
  { type: 'image/x-xpixmap', extensions: ['.xpm'] },
  { type: 'image/x-xwindowdump', extensions: ['.xwd'] },
  { type: 'message/rfc822', extensions: ['.eml', '.mht', '.mhtml', '.mime', '.nws'] },
  { type: 'model/iges', extensions: ['.iges', '.igs'] },
  { type: 'model/mesh', extensions: ['.mesh', '.msh', '.silo'] },
  { type: 'model/vnd.dwf', extensions: ['.dwf'] },
  { type: 'model/vnd.gdl', extensions: ['.gdl'] },
  { type: 'model/vnd.gtw', extensions: ['.gtw'] },
  { type: 'model/vnd.mts', extensions: ['.mts'] },
  { type: 'model/vnd.vtu', extensions: ['.vtu'] },
  { type: 'model/vrml', extensions: ['.vrml', '.wrl'] },
  { type: 'text/calendar', extensions: ['.ics', '.ifb'] },
  { type: 'text/css', extensions: ['.css'] },
  { type: 'text/csv', extensions: ['.csv'] },
  { type: 'text/html', extensions: ['.htm', '.html'] },
  { type: 'text/javascript', extensions: ['.js'] },
  { type: 'text/markdown', extensions: ['.md', '.markdown', '.mdown', '.markdn'] },
  { type: 'text/mathml', extensions: ['.mathml', '.mml'] },
  {
    type: 'text/plain',
    extensions: ['.conf', '.def', '.diff', '.in', '.ksh', '.list', '.log', '.pl', '.text', '.txt'],
  },
  { type: 'text/prs.lines.tag', extensions: ['.dsc'] },
  { type: 'text/richtext', extensions: ['.rtx'] },
  { type: 'text/sgml', extensions: ['.sgm', '.sgml'] },
  { type: 'text/tab-separated-values', extensions: ['.tsv'] },
  { type: 'text/troff', extensions: ['.man', '.me', '.ms', '.roff', '.t', '.tr'] },
  { type: 'text/uri-list', extensions: ['.uri', '.uris', '.urls'] },
  { type: 'text/vnd.curl', extensions: ['.curl'] },
  { type: 'text/vnd.curl.dcurl', extensions: ['.dcurl'] },
  { type: 'text/vnd.curl.mcurl', extensions: ['.mcurl'] },
  { type: 'text/vnd.curl.scurl', extensions: ['.scurl'] },
  { type: 'text/vnd.fly', extensions: ['.fly'] },
  { type: 'text/vnd.fmi.flexstor', extensions: ['.flx'] },
  { type: 'text/vnd.graphviz', extensions: ['.gv'] },
  { type: 'text/vnd.in3d.3dml', extensions: ['.3dml'] },
  { type: 'text/vnd.in3d.spot', extensions: ['.spot'] },
  { type: 'text/vnd.sun.j2me.app-descriptor', extensions: ['.jad'] },
  { type: 'text/vnd.wap.si', extensions: ['.si'] },
  { type: 'text/vnd.wap.sl', extensions: ['.sl'] },
  { type: 'text/vnd.wap.wml', extensions: ['.wml'] },
  { type: 'text/vnd.wap.wmlscript', extensions: ['.wmls'] },
  { type: 'text/x-asm', extensions: ['.asm', '.s'] },
  { type: 'text/x-c', extensions: ['.c', '.cc', '.cpp', '.cxx', '.dic', '.h', '.hh'] },
  { type: 'text/x-fortran', extensions: ['.f', '.f77', '.f90', '.for'] },
  { type: 'text/x-java-source', extensions: ['.java'] },
  { type: 'text/x-pascal', extensions: ['.p', '.pas', '.pp', '.inc'] },
  { type: 'text/x-python', extensions: ['.py'] },
  { type: 'text/x-setext', extensions: ['.etx'] },
  { type: 'text/x-uuencode', extensions: ['.uu'] },
  { type: 'text/x-vcalendar', extensions: ['.vcs'] },
  { type: 'text/x-vcard', extensions: ['.vcf'] },
  { type: 'video/3gpp', extensions: ['.3gp'] },
  { type: 'video/3gpp2', extensions: ['.3g2'] },
  { type: 'video/h261', extensions: ['.h261'] },
  { type: 'video/h263', extensions: ['.h263'] },
  { type: 'video/h264', extensions: ['.h264'] },
  { type: 'video/jpeg', extensions: ['.jpgv'] },
  { type: 'video/jpm', extensions: ['.jpgm', '.jpm'] },
  { type: 'video/mj2', extensions: ['.mj2', '.mjp2'] },
  { type: 'video/mp4', extensions: ['.mp4', '.mp4v', '.mpg4'] },
  { type: 'video/mpeg', extensions: ['.m1v', '.m2v', '.mpa', '.mpe', '.mpeg', '.mpg'] },
  { type: 'video/ogg', extensions: ['.ogv'] },
  { type: 'video/quicktime', extensions: ['.mov', '.qt'] },
  { type: 'video/vnd.fvt', extensions: ['.fvt'] },
  { type: 'video/vnd.mpegurl', extensions: ['.m4u', '.mxu'] },
  { type: 'video/vnd.ms-playready.media.pyv', extensions: ['.pyv'] },
  { type: 'video/vnd.vivo', extensions: ['.viv'] },
  { type: 'video/webm', extensions: ['.webm'] },
  { type: 'video/x-f4v', extensions: ['.f4v'] },
  { type: 'video/x-fli', extensions: ['.fli'] },
  { type: 'video/x-flv', extensions: ['.flv'] },
  { type: 'video/x-m4v', extensions: ['.m4v'] },
  { type: 'video/x-matroska', extensions: ['.mkv'] },
  { type: 'video/x-ms-asf', extensions: ['.asf', '.asx'] },
  { type: 'video/x-ms-wm', extensions: ['.wm'] },
  { type: 'video/x-ms-wmv', extensions: ['.wmv'] },
  { type: 'video/x-ms-wmx', extensions: ['.wmx'] },
  { type: 'video/x-ms-wvx', extensions: ['.wvx'] },
  { type: 'video/x-msvideo', extensions: ['.avi'] },
  { type: 'video/x-sgi-movie', extensions: ['.movie'] },
  { type: 'x-conference/x-cooltalk', extensions: ['.ice'] },
]

/**
 * Map(.ext => 'MIME-Type')
 */
export const MIMETypesMap = new Map<string, string>()
MIMETypes.forEach(({ type, extensions }) => {
  extensions.forEach(extension => {
    MIMETypesMap.set(extension, type)
  })
})
